# Generated by Django 4.2.6 on 2023-11-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[(0, "Pending"), (1, "Successful"), (2, "Declined")],
                        default=0,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            (0, "Cash on Delivery"),
                            (1, "Paypal"),
                            (2, "Credit Card"),
                            (3, "Bank Transfer"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
