# Generated by Django 4.2.6 on 2023-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0004_alter_payment_description_alter_payment_payment_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("successful", "successful"),
                    ("declined", "declined"),
                ],
                default="pending",
            ),
        ),
    ]
