# Generated by Django 4.2.6 on 2023-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
    ]
