# Generated by Django 4.2.6 on 2023-11-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_alter_payment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("cash", "cash on delivery"),
                    ("paypal", "paypal"),
                    ("cc", "credit card"),
                    ("transfer", "Bank Transfer"),
                ],
                default="cash",
            ),
        ),
    ]
