# Generated by Django 4.2.6 on 2023-11-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon", models.CharField(max_length=255, unique=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "category",
                    models.CharField(
                        choices=[("percentage", "percentage"), ("cash", "cash")],
                        default="cash",
                    ),
                ),
            ],
        ),
    ]
