# Generated by Django 4.2.6 on 2023-11-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
